inherit_from:
  - .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

plugins:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'tmp/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 180

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Style/ArgumentsForwarding:
  Enabled: false

Style/DateTime:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - 'bin/release'
    - 'bin/tag'

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/HashEachMethods:
  Enabled: true

Style/HashSyntax:
  Enabled: true
  EnforcedShorthandSyntax: either

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ModuleLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Metrics/ClassLength:
  CountAsOne:
    - array
    - hash
    - heredoc

Naming/InclusiveLanguage:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribedClass:
  SkipBlocks: true

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Max: 6

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NoExpectationExample:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/SortMetadata:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false
